#include "Conveyor.h"

#include "globals.h"
  
extern conveyorNeighbourState(CELL*,int,int);

void 
  conveyorUpdateCellState8New(CELL *celluar)
{
  int neighbour,neighbour_state;
  
  celluar->isUpdated = TRUE;

  if(celluar->state & CONVEYOR_CONTROL ||
     celluar->state & 
     (CONVEYOR_UP|CONVEYOR_DOWN|CONVEYOR_RIGHT|CONVEYOR_LEFT) ||
     celluar->state & CONVEYOR_BROKEN)
    {
      celluar->newstate 
        = celluar->state & 
          (CONVEYOR_CONTROL|CONVEYOR_UP|CONVEYOR_DOWN|CONVEYOR_RIGHT|CONVEYOR_LEFT|CONVEYOR_BROKEN);
      return;
    }
  
  neighbour=conveyorNeighbourState(celluar,8,FALSE);
  
#ifdef __CELLapist__
  if(neighbour)
    celluar->color=1;
#endif /* __CELLapist */
  
  switch(neighbour)
    {
/******
  1 information (8) 
******/
     case CONVEYOR_UP:
      celluar->newstate = CONVEYOR_UP;
      break;
     case CONVEYOR_DOWN:
      celluar->newstate = CONVEYOR_DOWN;
      break;
     case CONVEYOR_RIGHT:
      celluar->newstate = CONVEYOR_RIGHT;
      break;
     case CONVEYOR_LEFT:
      celluar->newstate = CONVEYOR_LEFT;
      break;
     case CONVEYOR_UP_RIGHT:
     case CONVEYOR_UP_LEFT:
     case CONVEYOR_DOWN_RIGHT:
     case CONVEYOR_DOWN_LEFT:
      celluar->newstate = CONVEYOR_UP|CONVEYOR_RIGHT|CONVEYOR_DOWN|CONVEYOR_LEFT;
      break;
      
/******
  2 information (28) 
******/
      /*      neighbour (8) */
     case CONVEYOR_UP|CONVEYOR_UP_RIGHT:
      celluar->newstate = CONVEYOR_UP;
      break;
     case CONVEYOR_UP|CONVEYOR_UP_LEFT:
      celluar->newstate = CONVEYOR_UP;
      break;
     case CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT:
      celluar->newstate = CONVEYOR_DOWN;
      break;
     case CONVEYOR_DOWN|CONVEYOR_DOWN_LEFT:
      celluar->newstate = CONVEYOR_DOWN;
      break;
     case CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT:
      celluar->newstate = CONVEYOR_RIGHT;
      break;
     case CONVEYOR_RIGHT|CONVEYOR_DOWN_RIGHT:
      celluar->newstate = CONVEYOR_RIGHT;
      break;
     case CONVEYOR_LEFT|CONVEYOR_UP_LEFT:
      celluar->newstate = CONVEYOR_LEFT;
      break;
     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT:
      celluar->newstate = CONVEYOR_LEFT;
      break;
      
      /*  non-neighbour (20)*/
      /*     1 space (8) */
     case CONVEYOR_UP|CONVEYOR_RIGHT:
      celluar->newstate = CONVEYOR_UP;
      break;
     case CONVEYOR_UP|CONVEYOR_LEFT:
      celluar->newstate = CONVEYOR_LEFT;
      break;
     case CONVEYOR_DOWN|CONVEYOR_RIGHT:
      celluar->newstate = CONVEYOR_RIGHT;
      break;
     case CONVEYOR_DOWN|CONVEYOR_LEFT:
      celluar->newstate = CONVEYOR_DOWN;
      break;
     case CONVEYOR_UP_RIGHT|CONVEYOR_UP_LEFT:
     case CONVEYOR_UP_RIGHT|CONVEYOR_DOWN_RIGHT:
     case CONVEYOR_UP_LEFT|CONVEYOR_DOWN_LEFT:
     case CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN_RIGHT:
      celluar->newstate = CONVEYOR_UP|CONVEYOR_RIGHT|CONVEYOR_DOWN|CONVEYOR_LEFT;
      break;
      /*     2 space (8) */
     case CONVEYOR_UP|CONVEYOR_DOWN_RIGHT:
     case CONVEYOR_UP|CONVEYOR_DOWN_LEFT:
      celluar->newstate = CONVEYOR_UP;
      break;
     case CONVEYOR_DOWN|CONVEYOR_UP_RIGHT:
     case CONVEYOR_DOWN|CONVEYOR_UP_LEFT:
      celluar->newstate = CONVEYOR_DOWN;
      break;
     case CONVEYOR_LEFT|CONVEYOR_UP_RIGHT:
     case CONVEYOR_LEFT|CONVEYOR_DOWN_RIGHT:
      celluar->newstate = CONVEYOR_LEFT;
      break;
     case CONVEYOR_RIGHT|CONVEYOR_UP_LEFT:
     case CONVEYOR_RIGHT|CONVEYOR_DOWN_LEFT:
      celluar->newstate = CONVEYOR_RIGHT;
      break;
      
      /*     3 space(opposite) (4) */
     case CONVEYOR_UP|CONVEYOR_DOWN:
      celluar->newstate = CONVEYOR_UP;
      break;
     case CONVEYOR_RIGHT|CONVEYOR_LEFT:
      celluar->newstate = CONVEYOR_RIGHT;
      break;
     case CONVEYOR_UP_RIGHT|CONVEYOR_DOWN_LEFT:
     case CONVEYOR_DOWN_RIGHT|CONVEYOR_UP_LEFT:
      celluar->newstate = CONVEYOR_UP|CONVEYOR_RIGHT|CONVEYOR_DOWN|CONVEYOR_LEFT;
      break;
      
      
/******
  3 information (56) 
******/
      /*   full neighbour (8) */
     case CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_UP_LEFT:
      celluar->newstate = CONVEYOR_UP;
      break;
     case CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT:
      celluar->newstate = CONVEYOR_LEFT;
      break;
     case CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT:
      celluar->newstate = CONVEYOR_DOWN;
      break;
     case CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT:
      celluar->newstate = CONVEYOR_RIGHT;
      break;
     case CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_LEFT:
     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN:
     case CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT:
     case CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP:
      celluar->newstate = CONVEYOR_UP|CONVEYOR_RIGHT|CONVEYOR_DOWN|CONVEYOR_LEFT;
      break;
      
      /*   2 neighbour (32) */
     case CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_DOWN_LEFT:
     case CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_DOWN_RIGHT:
     case CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_DOWN:
     case CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_LEFT:
      
     case CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_DOWN_LEFT:
     case CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_DOWN_RIGHT:
     case CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_DOWN:
     case CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_RIGHT:
      celluar->newstate = CONVEYOR_UP;
      break;
      
     case CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_RIGHT:
     case CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_UP_RIGHT:
     case CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_DOWN_RIGHT:
     case CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_DOWN:
      
     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_RIGHT:
     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN_RIGHT:
     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_UP_RIGHT:
     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_UP:
      celluar->newstate = CONVEYOR_LEFT;
      break;
      
     case CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_UP:
     case CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_UP_RIGHT:
     case CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_UP_LEFT:
     case CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_RIGHT:
      
     case CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_UP:
     case CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_UP_RIGHT:
     case CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_UP_LEFT:
     case CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_LEFT:
      celluar->newstate = CONVEYOR_DOWN;
      break;
      
     case CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_LEFT:
     case CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_UP_LEFT:
     case CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_DOWN_LEFT:
     case CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_UP:
      
     case CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_LEFT:
     case CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP_LEFT:
     case CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_DOWN_LEFT:
     case CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_DOWN:
      celluar->newstate = CONVEYOR_RIGHT;
      break;
      
      /*  non-neighbour (16) */
      /*    1-1space(8) */
     case CONVEYOR_UP|CONVEYOR_DOWN|CONVEYOR_RIGHT:
      celluar->newstate = CONVEYOR_RIGHT;
      break;
     case CONVEYOR_UP|CONVEYOR_DOWN|CONVEYOR_LEFT:
      celluar->newstate = CONVEYOR_LEFT;
      break;
     case CONVEYOR_UP|CONVEYOR_RIGHT|CONVEYOR_LEFT:
      celluar->newstate = CONVEYOR_UP;
      break;
     case CONVEYOR_DOWN|CONVEYOR_RIGHT|CONVEYOR_LEFT:
      celluar->newstate = CONVEYOR_DOWN;
      break;
      
     case CONVEYOR_UP_RIGHT|CONVEYOR_DOWN_RIGHT|CONVEYOR_DOWN_LEFT:
     case CONVEYOR_UP_LEFT|CONVEYOR_UP_RIGHT|CONVEYOR_DOWN_RIGHT:
     case CONVEYOR_DOWN_LEFT|CONVEYOR_UP_LEFT|CONVEYOR_UP_RIGHT:
     case CONVEYOR_DOWN_RIGHT|CONVEYOR_DOWN_LEFT|CONVEYOR_UP_LEFT:
      celluar->newstate = CONVEYOR_UP|CONVEYOR_RIGHT|CONVEYOR_DOWN|CONVEYOR_LEFT;
      break;
      
      /*    2-2space(8) */
     case CONVEYOR_UP|CONVEYOR_RIGHT|CONVEYOR_DOWN_LEFT:
     case CONVEYOR_UP|CONVEYOR_LEFT|CONVEYOR_DOWN_RIGHT:
     case CONVEYOR_DOWN|CONVEYOR_RIGHT|CONVEYOR_UP_LEFT:
     case CONVEYOR_DOWN|CONVEYOR_LEFT|CONVEYOR_UP_RIGHT:
      celluar->newstate = CONVEYOR_UP|CONVEYOR_RIGHT|CONVEYOR_DOWN|CONVEYOR_LEFT;
      break;
      
     case CONVEYOR_UP_RIGHT|CONVEYOR_DOWN_RIGHT|CONVEYOR_LEFT:
      celluar->newstate = CONVEYOR_LEFT;
      break;
     case CONVEYOR_UP_LEFT|CONVEYOR_UP_RIGHT|CONVEYOR_DOWN:
      celluar->newstate = CONVEYOR_DOWN;
      break;
     case CONVEYOR_DOWN_LEFT|CONVEYOR_UP_LEFT|CONVEYOR_RIGHT:
      celluar->newstate = CONVEYOR_RIGHT;
      break;
     case CONVEYOR_DOWN_RIGHT|CONVEYOR_DOWN_LEFT|CONVEYOR_UP:
      celluar->newstate = CONVEYOR_UP;
      break;
      
/******
  4 information (70) 
******/
      /*   full neighbour (8) */
     case CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_UP_LEFT:
      celluar->newstate = CONVEYOR_UP;
      break;
     case CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT:
      celluar->newstate = CONVEYOR_LEFT;
      break;
     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT:
      celluar->newstate = CONVEYOR_DOWN;
      break;
     case CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT:
      celluar->newstate = CONVEYOR_RIGHT;
      break;
     case CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_LEFT:
     case CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN:
     case CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT:
     case CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP:
      celluar->newstate = CONVEYOR_UP|CONVEYOR_RIGHT|CONVEYOR_DOWN|CONVEYOR_LEFT;
      break;
      /* 3 neighbour (24)*/
     case CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_DOWN_RIGHT:
     case CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_DOWN_LEFT:
     case CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_DOWN:
      celluar->newstate = CONVEYOR_UP;
      break;
      
     case CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_RIGHT:
     case CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_UP_RIGHT:
     case CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN_RIGHT:
      celluar->newstate = CONVEYOR_LEFT;
      break;
      
     case CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_UP:
     case CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_UP_RIGHT:
     case CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_UP_LEFT:
      celluar->newstate = CONVEYOR_DOWN;
      break;

     case CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_LEFT:
     case CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP_LEFT:
     case CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_DOWN_LEFT:
      celluar->newstate = CONVEYOR_RIGHT;
      break;
      

     case CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_DOWN_RIGHT:
     case CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_DOWN:
     case CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_RIGHT:
      
     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_UP_RIGHT:
     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_UP:
     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_RIGHT:
      
     case CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_UP_LEFT:
     case CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_UP:
     case CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_LEFT:
      
     case CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_DOWN_LEFT:
     case CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_DOWN:
     case CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_LEFT:
      celluar->newstate = CONVEYOR_UP|CONVEYOR_RIGHT|CONVEYOR_DOWN|CONVEYOR_LEFT;
      break;
      
      /* 2-1-1 neighbour(24) */
     case CONVEYOR_UP|CONVEYOR_UP_RIGHT|CONVEYOR_LEFT|CONVEYOR_DOWN:
     case CONVEYOR_UP|CONVEYOR_UP_RIGHT|CONVEYOR_LEFT|CONVEYOR_DOWN_RIGHT:
     case CONVEYOR_UP|CONVEYOR_UP_RIGHT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN_RIGHT:
      celluar->newstate = CONVEYOR_UP;
      break;
     case CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_DOWN|CONVEYOR_RIGHT:
     case CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_RIGHT:
     case CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN_RIGHT:
      celluar->newstate = CONVEYOR_UP;
      break;
     case CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_UP|CONVEYOR_LEFT:
     case CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_LEFT:
     case CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP_LEFT:
      celluar->newstate = CONVEYOR_DOWN;
      break;
     case CONVEYOR_DOWN|CONVEYOR_DOWN_LEFT|CONVEYOR_UP|CONVEYOR_RIGHT:
     case CONVEYOR_DOWN|CONVEYOR_DOWN_LEFT|CONVEYOR_UP_LEFT|CONVEYOR_RIGHT:
     case CONVEYOR_DOWN|CONVEYOR_DOWN_LEFT|CONVEYOR_UP_LEFT|CONVEYOR_UP_RIGHT:
      celluar->newstate = CONVEYOR_DOWN;
      break;
     case CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_LEFT|CONVEYOR_DOWN:
     case CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP_LEFT|CONVEYOR_DOWN:
     case CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP_LEFT|CONVEYOR_DOWN_LEFT:
      celluar->newstate = CONVEYOR_RIGHT;
      break;
     case CONVEYOR_RIGHT|CONVEYOR_DOWN_RIGHT|CONVEYOR_LEFT|CONVEYOR_UP:
     case CONVEYOR_RIGHT|CONVEYOR_DOWN_RIGHT|CONVEYOR_DOWN_LEFT|CONVEYOR_UP:
     case CONVEYOR_RIGHT|CONVEYOR_DOWN_RIGHT|CONVEYOR_UP_LEFT|CONVEYOR_DOWN_LEFT:
      celluar->newstate = CONVEYOR_RIGHT;
      break;
     case CONVEYOR_LEFT|CONVEYOR_UP_LEFT|CONVEYOR_RIGHT|CONVEYOR_DOWN:
     case CONVEYOR_LEFT|CONVEYOR_UP_LEFT|CONVEYOR_UP_RIGHT|CONVEYOR_DOWN:
     case CONVEYOR_LEFT|CONVEYOR_UP_LEFT|CONVEYOR_UP_RIGHT|CONVEYOR_DOWN_RIGHT:
      celluar->newstate = CONVEYOR_LEFT;
      break;
     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_RIGHT|CONVEYOR_UP:
     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN_RIGHT|CONVEYOR_UP:
     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN_RIGHT|CONVEYOR_UP_RIGHT:
      celluar->newstate = CONVEYOR_LEFT;
      break;
      
      /* 2-2 neighbour(12) */
     case CONVEYOR_UP|CONVEYOR_UP_RIGHT|CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT:
      celluar->newstate = CONVEYOR_UP;
      break;
     case CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_RIGHT|CONVEYOR_DOWN_RIGHT:
      celluar->newstate = CONVEYOR_RIGHT;
      break;
     case CONVEYOR_LEFT|CONVEYOR_UP_LEFT|CONVEYOR_DOWN_RIGHT|CONVEYOR_DOWN:
      celluar->newstate = CONVEYOR_LEFT;
      break;
     case CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_DOWN|CONVEYOR_DOWN_LEFT:
      celluar->newstate = CONVEYOR_DOWN;
      break;
      
     case CONVEYOR_UP|CONVEYOR_UP_RIGHT|CONVEYOR_DOWN|CONVEYOR_DOWN_LEFT:
     case CONVEYOR_UP|CONVEYOR_UP_RIGHT|CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT:
      celluar->newstate = CONVEYOR_UP;
      break;

     case CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_DOWN|CONVEYOR_DOWN_LEFT:
     case CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT:
      celluar->newstate = CONVEYOR_DOWN;
      break;
      
     case CONVEYOR_LEFT|CONVEYOR_UP_LEFT|CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT:
     case CONVEYOR_LEFT|CONVEYOR_UP_LEFT|CONVEYOR_RIGHT|CONVEYOR_DOWN_RIGHT:
      celluar->newstate = CONVEYOR_LEFT;
      break;
      
     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT:
     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_RIGHT|CONVEYOR_DOWN_RIGHT:
      celluar->newstate = CONVEYOR_RIGHT;
      break;
      
      /* non-neighbour(2) */
     case CONVEYOR_UP|CONVEYOR_DOWN|CONVEYOR_RIGHT|CONVEYOR_LEFT:
      celluar->newstate = CONVEYOR_UP;
      break;
     case CONVEYOR_UP_RIGHT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN_RIGHT|CONVEYOR_UP_LEFT:
      celluar->newstate = CONVEYOR_UP|CONVEYOR_RIGHT|CONVEYOR_DOWN|CONVEYOR_LEFT;
      break;
      
/******
  5 information (56) 
******/
      /*   full neighbour (8) */
     case CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|
       CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_LEFT:
       celluar->newstate = CONVEYOR_UP;
      break;

     case CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN:
      celluar->newstate = CONVEYOR_LEFT;
      break;

     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|
       CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT:
      celluar->newstate = CONVEYOR_DOWN;
      break;

     case CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|
       CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP:
      celluar->newstate = CONVEYOR_RIGHT;
      break;
      
     case CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|
       CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_UP_LEFT:
     case CONVEYOR_UP_RIGHT|CONVEYOR_UP|
       CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT:
     case CONVEYOR_UP_LEFT|CONVEYOR_LEFT|
       CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT:
     case CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|
       CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT:
      celluar->newstate = CONVEYOR_UP|CONVEYOR_RIGHT|CONVEYOR_DOWN|CONVEYOR_LEFT;
      break;
      
      /*   4 neighbour (16) */
     case CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|
       CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_DOWN:
     case CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|
       CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_DOWN_LEFT:
       celluar->newstate = CONVEYOR_UP;
      break;

     case CONVEYOR_UP|CONVEYOR_UP_LEFT|
       CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN_RIGHT:
     case CONVEYOR_UP|CONVEYOR_UP_LEFT|
       CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_RIGHT:
      celluar->newstate = CONVEYOR_LEFT;
      break;

     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|
       CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_UP_RIGHT:
     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|
       CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_UP:
      celluar->newstate = CONVEYOR_DOWN;
      break;

     case CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|
       CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP_LEFT:
     case CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|
       CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_LEFT:
      celluar->newstate = CONVEYOR_RIGHT;
      break;

     case CONVEYOR_UP_RIGHT|CONVEYOR_UP|
       CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_DOWN:
     case CONVEYOR_UP_RIGHT|CONVEYOR_UP|
       CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_DOWN_RIGHT:

     case CONVEYOR_UP_LEFT|CONVEYOR_LEFT|
       CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_RIGHT:
     case CONVEYOR_UP_LEFT|CONVEYOR_LEFT|
       CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_UP_RIGHT:

     case CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|
       CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_UP:
     case CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|
       CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_UP_LEFT:

     case CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|
       CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_LEFT:
     case CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|
       CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_DOWN_LEFT:
      celluar->newstate = CONVEYOR_UP|CONVEYOR_RIGHT|CONVEYOR_DOWN|CONVEYOR_LEFT;
      break;

      /*   3 neighbour (24) */
      /*    3-2 (16)*/
     case CONVEYOR_UP_RIGHT|CONVEYOR_UP|
       CONVEYOR_UP_LEFT|CONVEYOR_DOWN|CONVEYOR_DOWN_LEFT:
     case CONVEYOR_UP_RIGHT|CONVEYOR_UP|
       CONVEYOR_UP_LEFT|CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT:
      celluar->newstate = CONVEYOR_UP;
      break;

     case CONVEYOR_UP_LEFT|CONVEYOR_LEFT|
       CONVEYOR_DOWN_LEFT|CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT:
     case CONVEYOR_UP_LEFT|CONVEYOR_LEFT|
       CONVEYOR_DOWN_LEFT|CONVEYOR_RIGHT|CONVEYOR_DOWN_RIGHT:
      celluar->newstate = CONVEYOR_LEFT;
      break;

     case CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|
       CONVEYOR_DOWN_RIGHT|CONVEYOR_UP|CONVEYOR_UP_RIGHT:
     case CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|
       CONVEYOR_DOWN_RIGHT|CONVEYOR_UP|CONVEYOR_UP_LEFT:
      celluar->newstate = CONVEYOR_DOWN;
      break;

     case CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|
       CONVEYOR_UP_RIGHT|CONVEYOR_LEFT|CONVEYOR_UP_LEFT:
     case CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|
       CONVEYOR_UP_RIGHT|CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT:
      celluar->newstate = CONVEYOR_RIGHT;
      break;

     case CONVEYOR_UP|CONVEYOR_UP_LEFT|
       CONVEYOR_LEFT|CONVEYOR_DOWN_RIGHT|CONVEYOR_DOWN:
     case CONVEYOR_UP|CONVEYOR_UP_LEFT|
       CONVEYOR_LEFT|CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT:

     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|
       CONVEYOR_DOWN|CONVEYOR_UP_RIGHT|CONVEYOR_UP:
     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|
       CONVEYOR_DOWN|CONVEYOR_UP_RIGHT|CONVEYOR_RIGHT:

     case CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|
       CONVEYOR_RIGHT|CONVEYOR_UP_LEFT|CONVEYOR_UP:
     case CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|
       CONVEYOR_RIGHT|CONVEYOR_UP_LEFT|CONVEYOR_LEFT:

      case CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|
       CONVEYOR_UP|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN:
     case CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|
       CONVEYOR_UP|CONVEYOR_DOWN_LEFT|CONVEYOR_LEFT:
      celluar->newstate = CONVEYOR_UP|CONVEYOR_RIGHT|CONVEYOR_DOWN|CONVEYOR_LEFT;
      break;

      /*    3-1-1 (8)*/
     case CONVEYOR_UP_RIGHT|CONVEYOR_UP|
       CONVEYOR_UP_LEFT|CONVEYOR_DOWN_RIGHT|CONVEYOR_DOWN_LEFT:
      celluar->newstate = CONVEYOR_UP;
      break;

     case CONVEYOR_UP_LEFT|CONVEYOR_LEFT|
       CONVEYOR_DOWN_LEFT|CONVEYOR_UP_RIGHT|CONVEYOR_DOWN_RIGHT:
      celluar->newstate = CONVEYOR_LEFT;
      break;

     case CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|
       CONVEYOR_DOWN_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP_LEFT:
      celluar->newstate = CONVEYOR_DOWN;
      break;

     case CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|
       CONVEYOR_UP_RIGHT|CONVEYOR_UP_LEFT|CONVEYOR_DOWN_LEFT:
      celluar->newstate = CONVEYOR_RIGHT;
      break;

     case CONVEYOR_UP|CONVEYOR_UP_LEFT|
       CONVEYOR_LEFT|CONVEYOR_RIGHT|CONVEYOR_DOWN:

     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|
        CONVEYOR_DOWN|CONVEYOR_UP|CONVEYOR_RIGHT:

     case CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|
       CONVEYOR_RIGHT|CONVEYOR_UP|CONVEYOR_LEFT:

     case CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|
       CONVEYOR_UP|CONVEYOR_LEFT|CONVEYOR_DOWN:
      celluar->newstate = CONVEYOR_UP|CONVEYOR_RIGHT|CONVEYOR_DOWN|CONVEYOR_LEFT;
      break;
      
      /* 2-2-1 (8) */
     case CONVEYOR_UP|CONVEYOR_UP_RIGHT|CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|
      CONVEYOR_LEFT:
       celluar->newstate = CONVEYOR_LEFT;
      break;
     case CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_DOWN|CONVEYOR_DOWN_LEFT|
      CONVEYOR_RIGHT:
       celluar->newstate = CONVEYOR_RIGHT;
      break;
     case CONVEYOR_LEFT|CONVEYOR_UP_LEFT|CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|
      CONVEYOR_DOWN:
       celluar->newstate = CONVEYOR_DOWN;
      break;
     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_RIGHT|CONVEYOR_DOWN_RIGHT|
      CONVEYOR_UP:
       celluar->newstate = CONVEYOR_UP;
      break;
      
     case CONVEYOR_UP|CONVEYOR_UP_RIGHT|CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|
      CONVEYOR_DOWN_RIGHT:
     case CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_RIGHT|CONVEYOR_DOWN_RIGHT|
      CONVEYOR_DOWN_LEFT:
     case CONVEYOR_LEFT|CONVEYOR_UP_LEFT|CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|
      CONVEYOR_UP_RIGHT:
     case CONVEYOR_DOWN|CONVEYOR_DOWN_LEFT|CONVEYOR_UP_RIGHT|CONVEYOR_RIGHT|
      CONVEYOR_UP_LEFT:
       celluar->newstate = CONVEYOR_UP|CONVEYOR_RIGHT|CONVEYOR_DOWN|CONVEYOR_LEFT;
      break;
      
/******
  6 information (28) 
******/
      /*   full neighbour (8) */
     case CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|
       CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_LEFT:
       celluar->newstate = CONVEYOR_UP;
      break;

     case CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_UP_LEFT|
       CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN:
       celluar->newstate = CONVEYOR_LEFT;
      break;

     case CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|
       CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT:
       celluar->newstate = CONVEYOR_DOWN;
      break;

     case CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|
       CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP:
       celluar->newstate = CONVEYOR_RIGHT;
      break;

     case CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|
       CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_UP_LEFT:
     case CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP|
       CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT:
     case CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_LEFT|
       CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT:
     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|
       CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT:
       celluar->newstate = CONVEYOR_UP|CONVEYOR_RIGHT|CONVEYOR_DOWN|CONVEYOR_LEFT;
      break;

      /*   5 neighbour (8) */
     case CONVEYOR_DOWN|CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|
       CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_LEFT:
       celluar->newstate = CONVEYOR_UP;
      break;

     case CONVEYOR_RIGHT|CONVEYOR_UP|CONVEYOR_UP_LEFT|
       CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN:
       celluar->newstate = CONVEYOR_LEFT;
      break;

     case CONVEYOR_UP|CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|
       CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT:
       celluar->newstate = CONVEYOR_DOWN;
      break;

     case CONVEYOR_LEFT|CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|
       CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP:
       celluar->newstate = CONVEYOR_RIGHT;
      break;

     case CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|
       CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_UP_LEFT:
     case CONVEYOR_DOWN_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP|
       CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT:
     case CONVEYOR_UP_RIGHT|CONVEYOR_UP_LEFT|CONVEYOR_LEFT|
       CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT:
     case CONVEYOR_UP_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|
       CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT:
       celluar->newstate = CONVEYOR_UP|CONVEYOR_RIGHT|CONVEYOR_DOWN|CONVEYOR_LEFT;
      break;

      /*   4 neighbour (8) */
     case CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_UP_LEFT|
       CONVEYOR_DOWN|CONVEYOR_DOWN_LEFT:
       celluar->newstate = CONVEYOR_UP;
      break;

     case CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|
       CONVEYOR_RIGHT|CONVEYOR_DOWN_RIGHT:
       celluar->newstate = CONVEYOR_LEFT;
      break;

     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|
       CONVEYOR_UP|CONVEYOR_UP_RIGHT:
       celluar->newstate = CONVEYOR_DOWN;
      break;

     case CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|
       CONVEYOR_LEFT|CONVEYOR_UP_LEFT:
       celluar->newstate = CONVEYOR_RIGHT;
      break;

     case CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_LEFT|
       CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT:
     case CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|
       CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT:
     case CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|
       CONVEYOR_UP|CONVEYOR_UP_LEFT:
     case CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP|
       CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT:
       celluar->newstate = CONVEYOR_UP|CONVEYOR_RIGHT|CONVEYOR_DOWN|CONVEYOR_LEFT;
      break;

      /*   3 neighbour (4) */
     case CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_UP_LEFT|
       CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT:
       celluar->newstate = CONVEYOR_UP;
      break;

     case CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|
       CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT:
       celluar->newstate = CONVEYOR_RIGHT;
      break;

     case CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_LEFT|
       CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT:
     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|
       CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP:
       celluar->newstate = CONVEYOR_UP|CONVEYOR_RIGHT|CONVEYOR_DOWN|CONVEYOR_LEFT;
      break;

/******
  7 information (8) 
******/
      /* full neighbour(8) */
     case CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|
       CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT:
       celluar->newstate = CONVEYOR_UP;
      break;

     case CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_UP_LEFT|
       CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT:
       celluar->newstate = CONVEYOR_LEFT;
      break;

     case CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|
       CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT:
       celluar->newstate = CONVEYOR_DOWN;
      break;

     case CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|
       CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_UP_LEFT:
       celluar->newstate = CONVEYOR_RIGHT;
      break;

     case CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|
       CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_LEFT:
     case CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP|
       CONVEYOR_UP_LEFT|CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN:
     case CONVEYOR_UP|CONVEYOR_UP_LEFT|CONVEYOR_LEFT|
       CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT:
     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|
       CONVEYOR_DOWN_RIGHT|CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP:
       celluar->newstate = CONVEYOR_UP|CONVEYOR_RIGHT|CONVEYOR_DOWN|CONVEYOR_LEFT;
      break;

/******
  8 information (1)
******/
     case CONVEYOR_LEFT|CONVEYOR_DOWN_LEFT|CONVEYOR_DOWN|CONVEYOR_DOWN_RIGHT|
       CONVEYOR_RIGHT|CONVEYOR_UP_RIGHT|CONVEYOR_UP|CONVEYOR_UP_LEFT:
       celluar->newstate = CONVEYOR_UP|CONVEYOR_RIGHT|CONVEYOR_DOWN|CONVEYOR_LEFT;
      break;
    }
}  
